
services:
#  database:
#    image: mysql
#    container_name: database_alegra
#    restart: no
#    networks: 
#      - backend
#    ports:
#      - "127.0.0.1:3306:3306"
#    expose: 
#      - 3306
#    volumes:
#      - dbdata:/var/lib/mysql
#    environment:
#      - MYSQL_ROOT_PASSWORD=LaPs#D3v3l0pMen7
#      - MYSQL_DATABASE=alegra-test
 #     - MYSQL_USER=Laps
#      - MYSQL_PASSWORD=LaPs#D3v3l0pMen7
    
  cache:
    restart: no
    container_name: cache_alegra
    image: memcached
    networks: 
      - backend
    ports:
      - "127.0.0.1:11211:11211"
    expose: 
      - 11211

  backend:
    restart: always
    image: alegra-test-backend
    #container_name: backend-alegra
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: vip
    environment:
      - DB_HOST=database-1.cosfjltrhf00.us-east-1.rds.amazonaws.com
      - DB_PORT=3306
      - DB_DATABASE=test_alegra
      - DB_USERNAME=admin
      - DB_PASSWORD=L4pZDev-10129113

    command: bash -c "php artisan serve --host=0.0.0.0"
    ports:
      - "127.0.0.1:7000-7500:8000"
    expose:
      - 8000
    networks:
      - backend
    depends_on:
     # - database
      - cache
        
  frontend:
    #container_name: frontend-alegra
    image: alegra-test-frontend
    restart: always
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: vip
     
    #command: bash -c "npm run dev"
    ports:
      - "127.0.0.1:5100-5500:80"
    expose:
      - 5173
    networks:
      - backend
   


networks:
  backend:
    driver: bridge
    attachable: true

  frontend:
    driver: bridge
    attachable: true


  database:
    driver: bridge


  memcached:
    driver: bridge
 
volumes:
  dbdata:

